# `Numpy`

Las Cadenas de caracteres (o strings) nos permiten manipular datos textuales

## Ejemplo 1

Crear un array 

In [2]:
#importar la libreria numpy
import numpy as np
# array de dos dimensiones
a = np.array([[1,2,3],[4,5,6]])
print(a)



[[1 2 3]
 [4 5 6]]


In [3]:
#Mostrar Dimension del Array
print("Dimension del Array: ", a.ndim)

Dimension del Array:  2


In [4]:
# Mostrar los elementos del array
print("Numero de elementos del array: ", a.size)

Numero de elementos del array 6


In [5]:
# Mostrar Forma del array
print("forma del Array: ", a.shape)

forma del Array:  (2, 3)


In [6]:
# Mostrar el tipo del Array
print("Tipo de dato del Array: ", a.dtype)

Tipo de dato del Array:  int64


## `Ejemplo 2`

Crear otro array para realizar operaciones como la suma, y el producto

In [7]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 3], [2, 1, 3]])

print("La suma de el arreglo a y array b: ", a + b )

La suma de el arreglo a y array b:  [[2 3 6]
 [6 6 9]]


In [8]:
print("El producto del arreglo a y array b: ", a * b )

El producto del arreglo a y array b:  [[ 1  2  9]
 [ 8  5 18]]


In [10]:
print("La traspuesta del arreglo a y array b: ", np.dot(a, np.transpose(b)) )

La traspuesta del arreglo a y array b:  [[12 13]
 [27 31]]


### Particiona la cadena lenguaje_modificado a partir de un caracter especifico en este caso ;

In [9]:
palabras = lenguaje_modificado.split(';')
palabras

['Python', 'es', 'un', 'Lenguaje', 'de', 'Programación']

### Función `join()`

Sirve para unir un conjunto de cadenas de caracteres (texto) a partir de un caracter especifico

In [10]:
lenguaje_union = ' '.join(palabras)
lenguaje_union

'Python es un Lenguaje de Programación'

### Función `help()`
Permite obtener información (documentación) de una función.

In [11]:
help(str.join)

Help on method_descriptor:

join(self, iterable, /) unbound builtins.str method
    Concatenate any number of strings.

    The string whose method is called is inserted in between each given string.
    The result is returned as a new string.

    Example: '.'.join(['ab', 'pq', 'rs']) -> 'ab.pq.rs'



### Función `capitalize()`
De una cadena de caracteres devuelve en mayuscula la primer letra

In [13]:
lenguaje.capitalize()

'Python es un lenguaje de programación'

### Función `chr()`

Recibe como argumento un entero y devuelve una cadena con el caracter unicode

In [14]:
chr(45)

'-'

### Función `startwith()`

 devuelve un valor booleano True o False si coincide que la cadena inicie con el criterio enviado por parámetros en la función.

In [27]:
'Hola Mundo'.startswith('Ho')

True

### Función `endswith()`

Devuelve un valor booleano True o False so coincide con la cadena 

In [17]:
'Hola Mundo'.endswith('do')

True

### Función `find()`

Devuelve un valor númerico `0` si encuentra el criterio y `-1` si no coincide

In [18]:
'Esto es un Test'.find('esto')

-1

In [19]:
"Hola Hola".find('Hol')

0

### Función `isalnum()`

Devuelve un valor booleano `True` o `False` si la cadena contiene caracteres alfanumericos

In [20]:
"12345".isalnum()

True

### Función `isalpha()`

Devuelve un valor `True` o `False` si la cadena contiene caracteres alfabeticos.

In [23]:
'Python'.isalpha()

True